-- Create Groups table
CREATE TABLE IF NOT EXISTS groups (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    course TEXT NOT NULL,
    days TEXT NOT NULL,
    time TEXT NOT NULL,
    student_count INT DEFAULT 0,
    status TEXT DEFAULT 'active' CHECK (status IN ('active', 'archived')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- Create Students table
CREATE TABLE IF NOT EXISTS students (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    phone TEXT NOT NULL,
    age INT,
    source TEXT,
    gender TEXT,
    join_date DATE DEFAULT CURRENT_DATE,
    parent_name TEXT,
    parent_phone TEXT,
    group_name TEXT, -- Linked to group name for simplicity in your current logic
    payment_amount INT DEFAULT 0,
    comment TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- Create Teachers table
CREATE TABLE IF NOT EXISTS teachers (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    phone TEXT NOT NULL,
    age INT,
    start_date DATE DEFAULT CURRENT_DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- Create Payments table
CREATE TABLE IF NOT EXISTS payments (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    student_name TEXT NOT NULL,
    course TEXT NOT NULL,
    group_name TEXT,
    amount INT NOT NULL,
    date DATE DEFAULT CURRENT_DATE,
    next_payment_date DATE,
    status TEXT DEFAULT 'unpaid' CHECK (status IN ('paid', 'unpaid')),
    comment TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- Create Expenses table
CREATE TABLE IF NOT EXISTS expenses (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    amount INT NOT NULL,
    date DATE DEFAULT CURRENT_DATE,
    category TEXT DEFAULT 'other' CHECK (category IN ('rent', 'salary', 'utility', 'office', 'other')),
    comment TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- Enable RLS (Row Level Security) - For now, we allow public access for simplicity
-- In a real app, you would add policies for authenticated users
ALTER TABLE groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE students ENABLE ROW LEVEL SECURITY;
ALTER TABLE teachers ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE expenses ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read-write for all" ON groups FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read-write for all" ON students FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read-write for all" ON teachers FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read-write for all" ON payments FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read-write for all" ON expenses FOR ALL USING (true) WITH CHECK (true);
